### ISSUE TITLE
should import declarations reach renaming handlers?

### ISSUE THREAD

**Issue by guilhermejccavalcanti** [guilhermejccavalcanti/jFSTMerge#135] opened 2020-04-02 00:38 UTC
Import declarations are reaching renaming handlers, I don't think this is right because this is causing wrong matches ( import matched with abstract method): 

![image](https://user-images.githubusercontent.com/3333981/78198968-b1fc3600-7460-11ea-816e-5408474032b3.png)

Should imports reach renaming handlers @jvcoutinho ? Any particular reason for that?
They came from this is step:

![image](https://user-images.githubusercontent.com/3333981/78199032-ecfe6980-7460-11ea-9aa0-be8a8276bc34.png)

I believe there must be an extra filter, a filter for methods and constructor declarations in this step.

**Comment by pauloborba** [comment] 2020-04-02 15:06
@jvcoutinho it seems like we lost the filter that tries to match only elements of the same type. is that right @jvcoutinho?

**Comment by guilhermejccavalcanti** [comment] 2020-04-02 18:13
> 
> 
> @jvcoutinho it seems like we lost the filter that tries to match only elements of the same type. is that right @jvcoutinho?

superimposition is matching properly (same name, same type), this is a issue only for the handler.

**Comment by jvcoutinho** [comment] 2020-04-03 13:23
That's weird, it's never happened to me. There are actually some filters in later steps, for example:
https://github.com/guilhermejccavalcanti/jFSTMerge/blob/b0f553b03e1c9eb6eb345af0754bf0526c81c860/src/main/java/br/ufpe/cin/mergers/handlers/MethodAndConstructorRenamingAndDeletionHandler.java#L178-L186

But this only constrains terminals to match methods, so I agree with you we could increase the robustness.
But since this method is the same as the one in #134, I suppose the problem is the same: the body ";" was marked as substring of the import statement's body. If it's body was empty (as it should be), this shouldn't be a problem.

**Comment by pauloborba** [comment] 2020-04-03 14:33
@jvcoutinho where should we add the check for trying to match only elements of the same type? 

your second comment reinforces the need for improving the substring matching algorithm, right?

**Comment by guilhermejccavalcanti** [comment] 2020-04-04 19:53
> 
> 
> That's weird, it's never happened to me. There are actually some filters in later steps, for example:
> 
> https://github.com/guilhermejccavalcanti/jFSTMerge/blob/b0f553b03e1c9eb6eb345af0754bf0526c81c860/src/main/java/br/ufpe/cin/mergers/handlers/MethodAndConstructorRenamingAndDeletionHandler.java#L178-L186
> 
> But this only constrains terminals to match methods, so I agree with you we could increase the robustness.
> But since this method is the same as the one in #134, I suppose the problem is the same: the body ";" was marked as substring of the import statement's body. If it's body was empty (as it should be), this shouldn't be a problem.

@jvcoutinho the filter you mentioned only check the left and right trees, as you can see below(the import came from the base, which is not filtered):

![image](https://user-images.githubusercontent.com/3333981/78460136-c88ad300-7694-11ea-95f5-bc128c2fb14b.png)

**Closed** 2020-04-27 19:20 UTC
Labels: bug, question
